name: Sync Wiki to Pages
on:
  gollum:  # срабатывает при изменении Wiki
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki-temp
          cp -r wiki-temp/* docs/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs